version: "3"
services:
  config:
    image: com.nothing.whoami/config:0.0.1-SNAPSHOT
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.1"
          memory: 200M
      restart_policy:
        condition: on-failure
    ports:
      - "8888:8888"
    networks:
      - webnet

  eureka-service:
    image: com.nothing.whoami/eureka-service:0.0.1-SNAPSHOT
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.1"
          memory: 200M
      restart_policy:
        condition: on-failure
    ports:
      - "8761:8761"
    networks:
      - webnet

  reservation-service:
      image: com.nothing.whoami/reservation-service:0.0.1-SNAPSHOT
      deploy:
        replicas: 2
        resources:
          limits:
            cpus: "0.1"
            memory: 200M
        restart_policy:
          condition: on-failure
      ports:
        - "8000:8000"
      networks:
        - webnet

  reservation-client:
        image: com.nothing.whoami/reservation-client:0.0.1-SNAPSHOT
        deploy:
          replicas: 2
          resources:
            limits:
              cpus: "0.1"
              memory: 200M
          restart_policy:
            condition: on-failure
        ports:
          - "8050:8050"
        networks:
          - webnet
networks:
  webnet:
    driver: overlay
