server:
  port: ${PORT:8020}

spring:
  cloud:
    stream:
      bindings:
        sms_system_channel:
          binder: rabbit
          destination: sms.system.exchange
          contentType: application/json
          group: smsgroup