server:
  port: 10000

#sidecar:
  #port: 8000

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

hystrix:
    command:
        default:
            execution:
                isolation:
                    thread:
                        timeoutInMilliseconds: 10000

ribbon:
  ReadTimeout: 20000
  ConnectTimeout: 20000

zuul:
  host:
    connect-timeout-millis: 5000
    socket-timeout-millis: 10000
  add-host-header: true
  ignored-services: "*"
  routes:
    reservation-client:
      path: /reservation/**
      service-id: reservation-client
    auth-server:
      path: /uaa/**
      serviceId: auth-server
      sensitiveHeaders:
#      strip-prefix: false      # add uaa to auth-server path

security:
  oauth2:
    client:
      access-token-uri: http://auth-server/uaa/oauth/token
      user-authorization-uri: http://auth-server/uaa/oauth/authorize
      authentication-scheme: form
#      client-id: webapp
    resource:
      user-info-uri: http://auth-server/uaa/user
      prefer-token-info: false
  basic:
    enabled: false