server:
  port: 10000

#sidecar:
  #port: 8000

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false


zuul:
  ignored-services: "*"
  routes:
    reservation-client:
      path: /reservation/**
      service-id: reservation-client
#    recommend:
#      path: /recommend/**
#      url: http://recommend:9002/recommend