server:
  port: ${PORT:8050}

spring:
  zipkin:
    base-url: http://zipkin-server:9411

hystrix:
    command:
        default:
            execution:
                isolation:
                    thread:
                        timeoutInMilliseconds: 10000

ribbon:
  ReadTimeout: 20000
  ConnectTimeout: 20000